trigger:
- Dev
- Prod

pool: AWS-EC2-Agents
variables:
- group: stagin-cred

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).zip'
    ArtifactName: 'html-$(Build.BuildId)'
    ArtifactType: 'Container'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'git-lab.pem'
    retryCount: '3'
